# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lwfp0d2Tk2FWnr2nfKGCyAjl0Vz5VqOk
"""

# !pip install wandb -qU

import wandb
import os
from keras.datasets import fashion_mnist
import matplotlib.pyplot as plt

os.environ['WAND_NOTEBOOK_NAME'] = 'Q1'

# !wandb login c2d81ac4a00568bc9c2f420ec019b35bd24aac61

(trainX,trainy),(testX,testy) = fashion_mnist.load_data()

wandb.init(project='CS6910_A1',entity='cs22m064',name='question 1')

class_list = ['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']

i=0
data_images=[]
data_images_class=[]

while(len(data_images_class) < 10):
  if(class_list[trainy[i]] not in data_images_class):
    data_images.append(trainX[i])
    data_images_class.append(class_list[trainy[i]])
  i+=1

fig1 = plt.figure(figsize=(20,5)) 

for i in range(10):
    plt.subplot(2,5,i+1)   
    plt.xticks([])
    plt.yticks([]) 
    plt.imshow(data_images[i],cmap=plt.cm.binary)
    plt.xlabel(data_images_class[i])
    plt.grid(False)
plt.show()

wandb.log({"Sample Image for each class": fig1})
wandb.save()
wandb.finish()